export const ModalType = {
    ADD_LOP: "ADD_LOP",
    ADD_GIAOVIEN: "ADD_GIAOVIEN",
    ADD_SINHVIEN: "ADD_SINHVIEN",
    ADD_KHOA: "ADD_KHOA",
    ADD_HOITHAO: "ADD_HOITHAO",
    DETAIL_SINHVIEN: "DETAIL_SINHVIEN",
    DETAIL_GIAOVIEN: "DETAIL_GIAOVIEN",
    DELETE: "DELETE",
    DEFAULT: ""
}